import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Link href="/">
          <h1>My lovely apps</h1>
        </Link>
        <nav>
          <Link href="/dashboard">Dashboard</Link> |{" "}
          <Link href="/dashboard/settings">Settings</Link> |{" "}
          <Link href="/about">About</Link> |{" "}
          <Link href="/blog">Blog</Link> |{" "}
          <Link href="/blog-swr">Blog swr</Link> |{" "}
        </nav>
        <main>
          {children}
        </main>
        </body>
      </html>
    );
  }
